name: nix
description: Install Nix with the flake's experimental features and caches
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@v16
      with:
        extra-conf: |
          experimental-features = nix-command flakes pipe-operators
          extra-substituters = https://nix-community.cachix.org
          extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
