name: iso

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  iso:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-codeql: true
          remove-haskell: true
          remove-docker-images: true
      - uses: actions/checkout@v5
      - uses: ./.github/actions/nix
      - run: nix build .#iso
      - run: gh release create "$GITHUB_REF_NAME" result/iso/*.iso
        env:
          GH_TOKEN: ${{ github.token }}
