name: update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # daily

permissions:
  contents: write

concurrency: update

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/nix

      - run: nix flake update

      - name: Check and push
        run: |
          git diff --quiet flake.lock && exit 0
          nix eval .#checks.x86_64-linux --apply 'builtins.mapAttrs (_: d: d.drvPath)'
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
            commit -m "flake.lock: update" flake.lock
          git push
